import DateHistogramSentimentTrendCard
  from '@/components/Overview/PrimaryMacroTrends/DateHistogramSentimentTrend/DateHistogramSentimentTrendCard.tsx';

export default DateHistogramSentimentTrendCard;