limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;

limit_req_status 429;


server {

    listen 80;
    server_name localhost;

    return 301 https://$host$request_uri;
}


server {

    listen 443 ssl;
    server_name localhost;


    ssl_certificate /etc/nginx/certs/localhost.pem;
    ssl_certificate_key /etc/nginx/certs/localhost-key.pem;


    location / {

        limit_req zone=api_limit burst=20 nodelay;


        proxy_pass http://host.docker.internal:8082;


        proxy_set_header Host $host;

        proxy_set_header X-Real-IP $remote_addr;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_set_header X-Forwarded-Proto https;
    }
}