/*
 * This file is generated by jOOQ.
 */
package com.example.news.api.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Entity implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String value;
    private Integer entityTypeId;

    public Entity() {}

    public Entity(Entity value) {
        this.id = value.id;
        this.value = value.value;
        this.entityTypeId = value.entityTypeId;
    }

    public Entity(
        Integer id,
        String value,
        Integer entityTypeId
    ) {
        this.id = id;
        this.value = value;
        this.entityTypeId = entityTypeId;
    }

    /**
     * Getter for <code>public.entity.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.entity.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.entity.value</code>.
     */
    public String getValue() {
        return this.value;
    }

    /**
     * Setter for <code>public.entity.value</code>.
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Getter for <code>public.entity.entity_type_id</code>.
     */
    public Integer getEntityTypeId() {
        return this.entityTypeId;
    }

    /**
     * Setter for <code>public.entity.entity_type_id</code>.
     */
    public void setEntityTypeId(Integer entityTypeId) {
        this.entityTypeId = entityTypeId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Entity other = (Entity) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.value == null) {
            if (other.value != null)
                return false;
        }
        else if (!this.value.equals(other.value))
            return false;
        if (this.entityTypeId == null) {
            if (other.entityTypeId != null)
                return false;
        }
        else if (!this.entityTypeId.equals(other.entityTypeId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.value == null) ? 0 : this.value.hashCode());
        result = prime * result + ((this.entityTypeId == null) ? 0 : this.entityTypeId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Entity (");

        sb.append(id);
        sb.append(", ").append(value);
        sb.append(", ").append(entityTypeId);

        sb.append(")");
        return sb.toString();
    }
}
