/*
 * This file is generated by jOOQ.
 */
package com.example.news.api.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NewsEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer newsId;
    private Integer entityId;

    public NewsEntity() {}

    public NewsEntity(NewsEntity value) {
        this.id = value.id;
        this.newsId = value.newsId;
        this.entityId = value.entityId;
    }

    public NewsEntity(
        Integer id,
        Integer newsId,
        Integer entityId
    ) {
        this.id = id;
        this.newsId = newsId;
        this.entityId = entityId;
    }

    /**
     * Getter for <code>public.news_entity.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.news_entity.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.news_entity.news_id</code>.
     */
    public Integer getNewsId() {
        return this.newsId;
    }

    /**
     * Setter for <code>public.news_entity.news_id</code>.
     */
    public void setNewsId(Integer newsId) {
        this.newsId = newsId;
    }

    /**
     * Getter for <code>public.news_entity.entity_id</code>.
     */
    public Integer getEntityId() {
        return this.entityId;
    }

    /**
     * Setter for <code>public.news_entity.entity_id</code>.
     */
    public void setEntityId(Integer entityId) {
        this.entityId = entityId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final NewsEntity other = (NewsEntity) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.newsId == null) {
            if (other.newsId != null)
                return false;
        }
        else if (!this.newsId.equals(other.newsId))
            return false;
        if (this.entityId == null) {
            if (other.entityId != null)
                return false;
        }
        else if (!this.entityId.equals(other.entityId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.newsId == null) ? 0 : this.newsId.hashCode());
        result = prime * result + ((this.entityId == null) ? 0 : this.entityId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("NewsEntity (");

        sb.append(id);
        sb.append(", ").append(newsId);
        sb.append(", ").append(entityId);

        sb.append(")");
        return sb.toString();
    }
}
