/*
 * This file is generated by jOOQ.
 */
package com.example.news.api.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class News implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String title;
    private LocalDateTime publishDate;
    private String link;
    private String lang;
    private String fullText;
    private String summary;
    private String sentimentLabel;
    private BigDecimal sentiment;
    private Integer topicId;
    private Integer sourceId;

    public News() {}

    public News(News value) {
        this.id = value.id;
        this.title = value.title;
        this.publishDate = value.publishDate;
        this.link = value.link;
        this.lang = value.lang;
        this.fullText = value.fullText;
        this.summary = value.summary;
        this.sentimentLabel = value.sentimentLabel;
        this.sentiment = value.sentiment;
        this.topicId = value.topicId;
        this.sourceId = value.sourceId;
    }

    public News(
        Integer id,
        String title,
        LocalDateTime publishDate,
        String link,
        String lang,
        String fullText,
        String summary,
        String sentimentLabel,
        BigDecimal sentiment,
        Integer topicId,
        Integer sourceId
    ) {
        this.id = id;
        this.title = title;
        this.publishDate = publishDate;
        this.link = link;
        this.lang = lang;
        this.fullText = fullText;
        this.summary = summary;
        this.sentimentLabel = sentimentLabel;
        this.sentiment = sentiment;
        this.topicId = topicId;
        this.sourceId = sourceId;
    }

    /**
     * Getter for <code>public.news.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.news.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.news.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>public.news.title</code>.
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for <code>public.news.publish_date</code>.
     */
    public LocalDateTime getPublishDate() {
        return this.publishDate;
    }

    /**
     * Setter for <code>public.news.publish_date</code>.
     */
    public void setPublishDate(LocalDateTime publishDate) {
        this.publishDate = publishDate;
    }

    /**
     * Getter for <code>public.news.link</code>.
     */
    public String getLink() {
        return this.link;
    }

    /**
     * Setter for <code>public.news.link</code>.
     */
    public void setLink(String link) {
        this.link = link;
    }

    /**
     * Getter for <code>public.news.lang</code>.
     */
    public String getLang() {
        return this.lang;
    }

    /**
     * Setter for <code>public.news.lang</code>.
     */
    public void setLang(String lang) {
        this.lang = lang;
    }

    /**
     * Getter for <code>public.news.full_text</code>.
     */
    public String getFullText() {
        return this.fullText;
    }

    /**
     * Setter for <code>public.news.full_text</code>.
     */
    public void setFullText(String fullText) {
        this.fullText = fullText;
    }

    /**
     * Getter for <code>public.news.summary</code>.
     */
    public String getSummary() {
        return this.summary;
    }

    /**
     * Setter for <code>public.news.summary</code>.
     */
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * Getter for <code>public.news.sentiment_label</code>.
     */
    public String getSentimentLabel() {
        return this.sentimentLabel;
    }

    /**
     * Setter for <code>public.news.sentiment_label</code>.
     */
    public void setSentimentLabel(String sentimentLabel) {
        this.sentimentLabel = sentimentLabel;
    }

    /**
     * Getter for <code>public.news.sentiment</code>.
     */
    public BigDecimal getSentiment() {
        return this.sentiment;
    }

    /**
     * Setter for <code>public.news.sentiment</code>.
     */
    public void setSentiment(BigDecimal sentiment) {
        this.sentiment = sentiment;
    }

    /**
     * Getter for <code>public.news.topic_id</code>.
     */
    public Integer getTopicId() {
        return this.topicId;
    }

    /**
     * Setter for <code>public.news.topic_id</code>.
     */
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }

    /**
     * Getter for <code>public.news.source_id</code>.
     */
    public Integer getSourceId() {
        return this.sourceId;
    }

    /**
     * Setter for <code>public.news.source_id</code>.
     */
    public void setSourceId(Integer sourceId) {
        this.sourceId = sourceId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final News other = (News) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.publishDate == null) {
            if (other.publishDate != null)
                return false;
        }
        else if (!this.publishDate.equals(other.publishDate))
            return false;
        if (this.link == null) {
            if (other.link != null)
                return false;
        }
        else if (!this.link.equals(other.link))
            return false;
        if (this.lang == null) {
            if (other.lang != null)
                return false;
        }
        else if (!this.lang.equals(other.lang))
            return false;
        if (this.fullText == null) {
            if (other.fullText != null)
                return false;
        }
        else if (!this.fullText.equals(other.fullText))
            return false;
        if (this.summary == null) {
            if (other.summary != null)
                return false;
        }
        else if (!this.summary.equals(other.summary))
            return false;
        if (this.sentimentLabel == null) {
            if (other.sentimentLabel != null)
                return false;
        }
        else if (!this.sentimentLabel.equals(other.sentimentLabel))
            return false;
        if (this.sentiment == null) {
            if (other.sentiment != null)
                return false;
        }
        else if (!this.sentiment.equals(other.sentiment))
            return false;
        if (this.topicId == null) {
            if (other.topicId != null)
                return false;
        }
        else if (!this.topicId.equals(other.topicId))
            return false;
        if (this.sourceId == null) {
            if (other.sourceId != null)
                return false;
        }
        else if (!this.sourceId.equals(other.sourceId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.publishDate == null) ? 0 : this.publishDate.hashCode());
        result = prime * result + ((this.link == null) ? 0 : this.link.hashCode());
        result = prime * result + ((this.lang == null) ? 0 : this.lang.hashCode());
        result = prime * result + ((this.fullText == null) ? 0 : this.fullText.hashCode());
        result = prime * result + ((this.summary == null) ? 0 : this.summary.hashCode());
        result = prime * result + ((this.sentimentLabel == null) ? 0 : this.sentimentLabel.hashCode());
        result = prime * result + ((this.sentiment == null) ? 0 : this.sentiment.hashCode());
        result = prime * result + ((this.topicId == null) ? 0 : this.topicId.hashCode());
        result = prime * result + ((this.sourceId == null) ? 0 : this.sourceId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("News (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(publishDate);
        sb.append(", ").append(link);
        sb.append(", ").append(lang);
        sb.append(", ").append(fullText);
        sb.append(", ").append(summary);
        sb.append(", ").append(sentimentLabel);
        sb.append(", ").append(sentiment);
        sb.append(", ").append(topicId);
        sb.append(", ").append(sourceId);

        sb.append(")");
        return sb.toString();
    }
}
