spring:
  postgres:
    url: ${POSTGRES_URL}
    host: ${POSTGRES_HOST}
    port: ${POSTGRES_PORT}
    dbname: ${POSTGRES_DBNAME}
    authentication:
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

  neo4j:
    uri: ${NEO4J_URI}
    dbname: ${NEO4J_DB}
    authentication:
      username: ${NEO4J_USER}
      password: ${NEO4J_PASSWORD}

  elasticsearch:
    uris: ${ELASTIC_URL}

resilience4j:
  timelimiter:
    configs:
      default:
        timeoutDuration: 15s
        cancelRunningFuture: true

    instances:
      Neo4jGraph:
        baseConfig: default
      ElasticIndex:
        baseConfig: default
      PostgresArticle:
        baseConfig: default

  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

    instances:
      Neo4jGraph:
        baseConfig: default
      ElasticIndex:
        baseConfig: default
      PostgresArticle:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    tags:
      application: analytics-api
    distribution:
      percentiles-histogram:
        http.server.requests: true