import SignificantTermsAggregationChart
  from '@/components/Overview/EntityTopicIntelligenceBreakdown/SignificantTermsAggregation/SignificantTermsAggregationChart/SignificantTermsAggregationChart.tsx';

export default SignificantTermsAggregationChart;