/*
 * This file is generated by jOOQ.
 */
package com.example.news.api.jooq.tables;


import com.example.news.api.jooq.Keys;
import com.example.news.api.jooq.Public;
import com.example.news.api.jooq.tables.EntityType.EntityTypePath;
import com.example.news.api.jooq.tables.News.NewsPath;
import com.example.news.api.jooq.tables.NewsEntity.NewsEntityPath;
import com.example.news.api.jooq.tables.records.EntityRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Entity extends TableImpl<EntityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.entity</code>
     */
    public static final Entity ENTITY = new Entity();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EntityRecord> getRecordType() {
        return EntityRecord.class;
    }

    /**
     * The column <code>public.entity.id</code>.
     */
    public final TableField<EntityRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.entity.value</code>.
     */
    public final TableField<EntityRecord, String> VALUE = createField(DSL.name("value"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.entity.entity_type_id</code>.
     */
    public final TableField<EntityRecord, Integer> ENTITY_TYPE_ID = createField(DSL.name("entity_type_id"), SQLDataType.INTEGER, this, "");

    private Entity(Name alias, Table<EntityRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Entity(Name alias, Table<EntityRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.entity</code> table reference
     */
    public Entity(String alias) {
        this(DSL.name(alias), ENTITY);
    }

    /**
     * Create an aliased <code>public.entity</code> table reference
     */
    public Entity(Name alias) {
        this(alias, ENTITY);
    }

    /**
     * Create a <code>public.entity</code> table reference
     */
    public Entity() {
        this(DSL.name("entity"), null);
    }

    public <O extends Record> Entity(Table<O> path, ForeignKey<O, EntityRecord> childPath, InverseForeignKey<O, EntityRecord> parentPath) {
        super(path, childPath, parentPath, ENTITY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class EntityPath extends Entity implements Path<EntityRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> EntityPath(Table<O> path, ForeignKey<O, EntityRecord> childPath, InverseForeignKey<O, EntityRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private EntityPath(Name alias, Table<EntityRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public EntityPath as(String alias) {
            return new EntityPath(DSL.name(alias), this);
        }

        @Override
        public EntityPath as(Name alias) {
            return new EntityPath(alias, this);
        }

        @Override
        public EntityPath as(Table<?> alias) {
            return new EntityPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<EntityRecord, Integer> getIdentity() {
        return (Identity<EntityRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<EntityRecord> getPrimaryKey() {
        return Keys.ENTITY_PKEY;
    }

    @Override
    public List<UniqueKey<EntityRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.ENTITY_VALUE_KEY);
    }

    @Override
    public List<ForeignKey<EntityRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ENTITY__ENTITY_ENTITY_TYPE_ID_FKEY);
    }

    private transient EntityTypePath _entityType;

    /**
     * Get the implicit join path to the <code>public.entity_type</code> table.
     */
    public EntityTypePath entityType() {
        if (_entityType == null)
            _entityType = new EntityTypePath(this, Keys.ENTITY__ENTITY_ENTITY_TYPE_ID_FKEY, null);

        return _entityType;
    }

    private transient NewsEntityPath _newsEntity;

    /**
     * Get the implicit to-many join path to the <code>public.news_entity</code>
     * table
     */
    public NewsEntityPath newsEntity() {
        if (_newsEntity == null)
            _newsEntity = new NewsEntityPath(this, null, Keys.NEWS_ENTITY__NEWS_ENTITY_ENTITY_ID_FKEY.getInverseKey());

        return _newsEntity;
    }

    /**
     * Get the implicit many-to-many join path to the <code>public.news</code>
     * table
     */
    public NewsPath news() {
        return newsEntity().news();
    }

    @Override
    public Entity as(String alias) {
        return new Entity(DSL.name(alias), this);
    }

    @Override
    public Entity as(Name alias) {
        return new Entity(alias, this);
    }

    @Override
    public Entity as(Table<?> alias) {
        return new Entity(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Entity rename(String name) {
        return new Entity(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Entity rename(Name name) {
        return new Entity(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Entity rename(Table<?> name) {
        return new Entity(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Entity where(Condition condition) {
        return new Entity(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Entity where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Entity where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Entity where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Entity where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Entity where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Entity where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Entity where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Entity whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Entity whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
