/*
 * This file is generated by jOOQ.
 */
package com.example.news.api.jooq.tables;


import com.example.news.api.jooq.Keys;
import com.example.news.api.jooq.Public;
import com.example.news.api.jooq.tables.Entity.EntityPath;
import com.example.news.api.jooq.tables.records.EntityTypeRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EntityType extends TableImpl<EntityTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.entity_type</code>
     */
    public static final EntityType ENTITY_TYPE = new EntityType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EntityTypeRecord> getRecordType() {
        return EntityTypeRecord.class;
    }

    /**
     * The column <code>public.entity_type.id</code>.
     */
    public final TableField<EntityTypeRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.entity_type.name</code>.
     */
    public final TableField<EntityTypeRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB, this, "");

    private EntityType(Name alias, Table<EntityTypeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private EntityType(Name alias, Table<EntityTypeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.entity_type</code> table reference
     */
    public EntityType(String alias) {
        this(DSL.name(alias), ENTITY_TYPE);
    }

    /**
     * Create an aliased <code>public.entity_type</code> table reference
     */
    public EntityType(Name alias) {
        this(alias, ENTITY_TYPE);
    }

    /**
     * Create a <code>public.entity_type</code> table reference
     */
    public EntityType() {
        this(DSL.name("entity_type"), null);
    }

    public <O extends Record> EntityType(Table<O> path, ForeignKey<O, EntityTypeRecord> childPath, InverseForeignKey<O, EntityTypeRecord> parentPath) {
        super(path, childPath, parentPath, ENTITY_TYPE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class EntityTypePath extends EntityType implements Path<EntityTypeRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> EntityTypePath(Table<O> path, ForeignKey<O, EntityTypeRecord> childPath, InverseForeignKey<O, EntityTypeRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private EntityTypePath(Name alias, Table<EntityTypeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public EntityTypePath as(String alias) {
            return new EntityTypePath(DSL.name(alias), this);
        }

        @Override
        public EntityTypePath as(Name alias) {
            return new EntityTypePath(alias, this);
        }

        @Override
        public EntityTypePath as(Table<?> alias) {
            return new EntityTypePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<EntityTypeRecord, Integer> getIdentity() {
        return (Identity<EntityTypeRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<EntityTypeRecord> getPrimaryKey() {
        return Keys.ENTITY_TYPE_PKEY;
    }

    @Override
    public List<UniqueKey<EntityTypeRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.ENTITY_TYPE_UNIQUE_TYPE);
    }

    private transient EntityPath _entity;

    /**
     * Get the implicit to-many join path to the <code>public.entity</code>
     * table
     */
    public EntityPath entity() {
        if (_entity == null)
            _entity = new EntityPath(this, null, Keys.ENTITY__ENTITY_ENTITY_TYPE_ID_FKEY.getInverseKey());

        return _entity;
    }

    @Override
    public EntityType as(String alias) {
        return new EntityType(DSL.name(alias), this);
    }

    @Override
    public EntityType as(Name alias) {
        return new EntityType(alias, this);
    }

    @Override
    public EntityType as(Table<?> alias) {
        return new EntityType(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public EntityType rename(String name) {
        return new EntityType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EntityType rename(Name name) {
        return new EntityType(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public EntityType rename(Table<?> name) {
        return new EntityType(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EntityType where(Condition condition) {
        return new EntityType(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EntityType where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EntityType where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EntityType where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EntityType where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EntityType where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EntityType where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EntityType where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EntityType whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EntityType whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
