/*
 * This file is generated by jOOQ.
 */
package com.example.news.api.jooq.tables;


import com.example.news.api.jooq.Keys;
import com.example.news.api.jooq.Public;
import com.example.news.api.jooq.tables.records.EntityEntityRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EntityEntity extends TableImpl<EntityEntityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.entity_entity</code>
     */
    public static final EntityEntity ENTITY_ENTITY = new EntityEntity();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EntityEntityRecord> getRecordType() {
        return EntityEntityRecord.class;
    }

    /**
     * The column <code>public.entity_entity.id</code>.
     */
    public final TableField<EntityEntityRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.entity_entity.name</code>.
     */
    public final TableField<EntityEntityRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "");

    private EntityEntity(Name alias, Table<EntityEntityRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private EntityEntity(Name alias, Table<EntityEntityRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.entity_entity</code> table reference
     */
    public EntityEntity(String alias) {
        this(DSL.name(alias), ENTITY_ENTITY);
    }

    /**
     * Create an aliased <code>public.entity_entity</code> table reference
     */
    public EntityEntity(Name alias) {
        this(alias, ENTITY_ENTITY);
    }

    /**
     * Create a <code>public.entity_entity</code> table reference
     */
    public EntityEntity() {
        this(DSL.name("entity_entity"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<EntityEntityRecord> getPrimaryKey() {
        return Keys.ENTITY_ENTITY_PKEY;
    }

    @Override
    public EntityEntity as(String alias) {
        return new EntityEntity(DSL.name(alias), this);
    }

    @Override
    public EntityEntity as(Name alias) {
        return new EntityEntity(alias, this);
    }

    @Override
    public EntityEntity as(Table<?> alias) {
        return new EntityEntity(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public EntityEntity rename(String name) {
        return new EntityEntity(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EntityEntity rename(Name name) {
        return new EntityEntity(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public EntityEntity rename(Table<?> name) {
        return new EntityEntity(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EntityEntity where(Condition condition) {
        return new EntityEntity(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EntityEntity where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EntityEntity where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EntityEntity where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EntityEntity where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EntityEntity where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EntityEntity where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EntityEntity where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EntityEntity whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EntityEntity whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
