/*
 * This file is generated by jOOQ.
 */
package com.example.news.api.jooq.tables;


import com.example.news.api.jooq.Keys;
import com.example.news.api.jooq.Public;
import com.example.news.api.jooq.tables.Entity.EntityPath;
import com.example.news.api.jooq.tables.NewsEntity.NewsEntityPath;
import com.example.news.api.jooq.tables.Source.SourcePath;
import com.example.news.api.jooq.tables.Topic.TopicPath;
import com.example.news.api.jooq.tables.records.NewsRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class News extends TableImpl<NewsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.news</code>
     */
    public static final News NEWS = new News();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NewsRecord> getRecordType() {
        return NewsRecord.class;
    }

    /**
     * The column <code>public.news.id</code>.
     */
    public final TableField<NewsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.news.title</code>.
     */
    public final TableField<NewsRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.news.publish_date</code>.
     */
    public final TableField<NewsRecord, LocalDateTime> PUBLISH_DATE = createField(DSL.name("publish_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.news.link</code>.
     */
    public final TableField<NewsRecord, String> LINK = createField(DSL.name("link"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.news.lang</code>.
     */
    public final TableField<NewsRecord, String> LANG = createField(DSL.name("lang"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.news.full_text</code>.
     */
    public final TableField<NewsRecord, String> FULL_TEXT = createField(DSL.name("full_text"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.news.summary</code>.
     */
    public final TableField<NewsRecord, String> SUMMARY = createField(DSL.name("summary"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.news.sentiment_label</code>.
     */
    public final TableField<NewsRecord, String> SENTIMENT_LABEL = createField(DSL.name("sentiment_label"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.news.sentiment</code>.
     */
    public final TableField<NewsRecord, BigDecimal> SENTIMENT = createField(DSL.name("sentiment"), SQLDataType.NUMERIC(38, 2), this, "");

    /**
     * The column <code>public.news.topic_id</code>.
     */
    public final TableField<NewsRecord, Integer> TOPIC_ID = createField(DSL.name("topic_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.news.source_id</code>.
     */
    public final TableField<NewsRecord, Integer> SOURCE_ID = createField(DSL.name("source_id"), SQLDataType.INTEGER, this, "");

    private News(Name alias, Table<NewsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private News(Name alias, Table<NewsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.news</code> table reference
     */
    public News(String alias) {
        this(DSL.name(alias), NEWS);
    }

    /**
     * Create an aliased <code>public.news</code> table reference
     */
    public News(Name alias) {
        this(alias, NEWS);
    }

    /**
     * Create a <code>public.news</code> table reference
     */
    public News() {
        this(DSL.name("news"), null);
    }

    public <O extends Record> News(Table<O> path, ForeignKey<O, NewsRecord> childPath, InverseForeignKey<O, NewsRecord> parentPath) {
        super(path, childPath, parentPath, NEWS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class NewsPath extends News implements Path<NewsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> NewsPath(Table<O> path, ForeignKey<O, NewsRecord> childPath, InverseForeignKey<O, NewsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private NewsPath(Name alias, Table<NewsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public NewsPath as(String alias) {
            return new NewsPath(DSL.name(alias), this);
        }

        @Override
        public NewsPath as(Name alias) {
            return new NewsPath(alias, this);
        }

        @Override
        public NewsPath as(Table<?> alias) {
            return new NewsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<NewsRecord, Integer> getIdentity() {
        return (Identity<NewsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<NewsRecord> getPrimaryKey() {
        return Keys.NEWS_PKEY;
    }

    @Override
    public List<UniqueKey<NewsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.NEWS_LINK_KEY);
    }

    @Override
    public List<ForeignKey<NewsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.NEWS__NEWS_SOURCE_ID_FKEY, Keys.NEWS__NEWS_TOPIC_ID_FKEY);
    }

    private transient SourcePath _source;

    /**
     * Get the implicit join path to the <code>public.source</code> table.
     */
    public SourcePath source() {
        if (_source == null)
            _source = new SourcePath(this, Keys.NEWS__NEWS_SOURCE_ID_FKEY, null);

        return _source;
    }

    private transient TopicPath _topic;

    /**
     * Get the implicit join path to the <code>public.topic</code> table.
     */
    public TopicPath topic() {
        if (_topic == null)
            _topic = new TopicPath(this, Keys.NEWS__NEWS_TOPIC_ID_FKEY, null);

        return _topic;
    }

    private transient NewsEntityPath _newsEntity;

    /**
     * Get the implicit to-many join path to the <code>public.news_entity</code>
     * table
     */
    public NewsEntityPath newsEntity() {
        if (_newsEntity == null)
            _newsEntity = new NewsEntityPath(this, null, Keys.NEWS_ENTITY__NEWS_ENTITY_NEWS_ID_FKEY.getInverseKey());

        return _newsEntity;
    }

    /**
     * Get the implicit many-to-many join path to the <code>public.entity</code>
     * table
     */
    public EntityPath entity() {
        return newsEntity().entity();
    }

    @Override
    public News as(String alias) {
        return new News(DSL.name(alias), this);
    }

    @Override
    public News as(Name alias) {
        return new News(alias, this);
    }

    @Override
    public News as(Table<?> alias) {
        return new News(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public News rename(String name) {
        return new News(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public News rename(Name name) {
        return new News(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public News rename(Table<?> name) {
        return new News(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public News where(Condition condition) {
        return new News(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public News where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public News where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public News where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public News where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public News where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public News where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public News where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public News whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public News whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
