/*
 * This file is generated by jOOQ.
 */
package com.example.news.api.jooq.tables;


import com.example.news.api.jooq.Keys;
import com.example.news.api.jooq.Public;
import com.example.news.api.jooq.tables.Entity.EntityPath;
import com.example.news.api.jooq.tables.News.NewsPath;
import com.example.news.api.jooq.tables.records.NewsEntityRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NewsEntity extends TableImpl<NewsEntityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.news_entity</code>
     */
    public static final NewsEntity NEWS_ENTITY = new NewsEntity();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NewsEntityRecord> getRecordType() {
        return NewsEntityRecord.class;
    }

    /**
     * The column <code>public.news_entity.id</code>.
     */
    public final TableField<NewsEntityRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.news_entity.news_id</code>.
     */
    public final TableField<NewsEntityRecord, Integer> NEWS_ID = createField(DSL.name("news_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.news_entity.entity_id</code>.
     */
    public final TableField<NewsEntityRecord, Integer> ENTITY_ID = createField(DSL.name("entity_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private NewsEntity(Name alias, Table<NewsEntityRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private NewsEntity(Name alias, Table<NewsEntityRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.news_entity</code> table reference
     */
    public NewsEntity(String alias) {
        this(DSL.name(alias), NEWS_ENTITY);
    }

    /**
     * Create an aliased <code>public.news_entity</code> table reference
     */
    public NewsEntity(Name alias) {
        this(alias, NEWS_ENTITY);
    }

    /**
     * Create a <code>public.news_entity</code> table reference
     */
    public NewsEntity() {
        this(DSL.name("news_entity"), null);
    }

    public <O extends Record> NewsEntity(Table<O> path, ForeignKey<O, NewsEntityRecord> childPath, InverseForeignKey<O, NewsEntityRecord> parentPath) {
        super(path, childPath, parentPath, NEWS_ENTITY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class NewsEntityPath extends NewsEntity implements Path<NewsEntityRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> NewsEntityPath(Table<O> path, ForeignKey<O, NewsEntityRecord> childPath, InverseForeignKey<O, NewsEntityRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private NewsEntityPath(Name alias, Table<NewsEntityRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public NewsEntityPath as(String alias) {
            return new NewsEntityPath(DSL.name(alias), this);
        }

        @Override
        public NewsEntityPath as(Name alias) {
            return new NewsEntityPath(alias, this);
        }

        @Override
        public NewsEntityPath as(Table<?> alias) {
            return new NewsEntityPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<NewsEntityRecord, Integer> getIdentity() {
        return (Identity<NewsEntityRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<NewsEntityRecord> getPrimaryKey() {
        return Keys.NEWS_ENTITY_PKEY;
    }

    @Override
    public List<UniqueKey<NewsEntityRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.NEWS_ENTITY_NEWS_ID_ENTITY_ID_KEY);
    }

    @Override
    public List<ForeignKey<NewsEntityRecord, ?>> getReferences() {
        return Arrays.asList(Keys.NEWS_ENTITY__NEWS_ENTITY_ENTITY_ID_FKEY, Keys.NEWS_ENTITY__NEWS_ENTITY_NEWS_ID_FKEY);
    }

    private transient EntityPath _entity;

    /**
     * Get the implicit join path to the <code>public.entity</code> table.
     */
    public EntityPath entity() {
        if (_entity == null)
            _entity = new EntityPath(this, Keys.NEWS_ENTITY__NEWS_ENTITY_ENTITY_ID_FKEY, null);

        return _entity;
    }

    private transient NewsPath _news;

    /**
     * Get the implicit join path to the <code>public.news</code> table.
     */
    public NewsPath news() {
        if (_news == null)
            _news = new NewsPath(this, Keys.NEWS_ENTITY__NEWS_ENTITY_NEWS_ID_FKEY, null);

        return _news;
    }

    @Override
    public NewsEntity as(String alias) {
        return new NewsEntity(DSL.name(alias), this);
    }

    @Override
    public NewsEntity as(Name alias) {
        return new NewsEntity(alias, this);
    }

    @Override
    public NewsEntity as(Table<?> alias) {
        return new NewsEntity(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public NewsEntity rename(String name) {
        return new NewsEntity(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public NewsEntity rename(Name name) {
        return new NewsEntity(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public NewsEntity rename(Table<?> name) {
        return new NewsEntity(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NewsEntity where(Condition condition) {
        return new NewsEntity(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NewsEntity where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NewsEntity where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NewsEntity where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NewsEntity where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NewsEntity where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NewsEntity where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NewsEntity where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NewsEntity whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NewsEntity whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
