/*
 * This file is generated by jOOQ.
 */
package com.example.news.api.jooq.tables;


import com.example.news.api.jooq.Keys;
import com.example.news.api.jooq.Public;
import com.example.news.api.jooq.tables.News.NewsPath;
import com.example.news.api.jooq.tables.records.TopicRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Topic extends TableImpl<TopicRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.topic</code>
     */
    public static final Topic TOPIC = new Topic();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TopicRecord> getRecordType() {
        return TopicRecord.class;
    }

    /**
     * The column <code>public.topic.id</code>.
     */
    public final TableField<TopicRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.topic.name</code>.
     */
    public final TableField<TopicRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    private Topic(Name alias, Table<TopicRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Topic(Name alias, Table<TopicRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.topic</code> table reference
     */
    public Topic(String alias) {
        this(DSL.name(alias), TOPIC);
    }

    /**
     * Create an aliased <code>public.topic</code> table reference
     */
    public Topic(Name alias) {
        this(alias, TOPIC);
    }

    /**
     * Create a <code>public.topic</code> table reference
     */
    public Topic() {
        this(DSL.name("topic"), null);
    }

    public <O extends Record> Topic(Table<O> path, ForeignKey<O, TopicRecord> childPath, InverseForeignKey<O, TopicRecord> parentPath) {
        super(path, childPath, parentPath, TOPIC);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TopicPath extends Topic implements Path<TopicRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TopicPath(Table<O> path, ForeignKey<O, TopicRecord> childPath, InverseForeignKey<O, TopicRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TopicPath(Name alias, Table<TopicRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TopicPath as(String alias) {
            return new TopicPath(DSL.name(alias), this);
        }

        @Override
        public TopicPath as(Name alias) {
            return new TopicPath(alias, this);
        }

        @Override
        public TopicPath as(Table<?> alias) {
            return new TopicPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<TopicRecord, Integer> getIdentity() {
        return (Identity<TopicRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<TopicRecord> getPrimaryKey() {
        return Keys.NEWS_CLASSIFICATION_PKEY;
    }

    @Override
    public List<UniqueKey<TopicRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.NEWS_CLASSIFICATION_CLASSIFICATION_KEY);
    }

    private transient NewsPath _news;

    /**
     * Get the implicit to-many join path to the <code>public.news</code> table
     */
    public NewsPath news() {
        if (_news == null)
            _news = new NewsPath(this, null, Keys.NEWS__NEWS_TOPIC_ID_FKEY.getInverseKey());

        return _news;
    }

    @Override
    public Topic as(String alias) {
        return new Topic(DSL.name(alias), this);
    }

    @Override
    public Topic as(Name alias) {
        return new Topic(alias, this);
    }

    @Override
    public Topic as(Table<?> alias) {
        return new Topic(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Topic rename(String name) {
        return new Topic(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Topic rename(Name name) {
        return new Topic(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Topic rename(Table<?> name) {
        return new Topic(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Topic where(Condition condition) {
        return new Topic(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Topic where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Topic where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Topic where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Topic where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Topic where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Topic where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Topic where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Topic whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Topic whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
