/*
 * This file is generated by jOOQ.
 */
package com.example.news.api.jooq.tables.records;


import com.example.news.api.jooq.tables.EntityEntity;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EntityEntityRecord extends UpdatableRecordImpl<EntityEntityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.entity_entity.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.entity_entity.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.entity_entity.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.entity_entity.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EntityEntityRecord
     */
    public EntityEntityRecord() {
        super(EntityEntity.ENTITY_ENTITY);
    }

    /**
     * Create a detached, initialised EntityEntityRecord
     */
    public EntityEntityRecord(Integer id, String name) {
        super(EntityEntity.ENTITY_ENTITY);

        setId(id);
        setName(name);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised EntityEntityRecord
     */
    public EntityEntityRecord(com.example.news.api.jooq.tables.pojos.EntityEntity value) {
        super(EntityEntity.ENTITY_ENTITY);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            resetChangedOnNotNull();
        }
    }
}
