/*
 * This file is generated by jOOQ.
 */
package com.example.news.api.jooq.tables.records;


import com.example.news.api.jooq.tables.Entity;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EntityRecord extends UpdatableRecordImpl<EntityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.entity.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.entity.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.entity.value</code>.
     */
    public void setValue(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.entity.value</code>.
     */
    public String getValue() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.entity.entity_type_id</code>.
     */
    public void setEntityTypeId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.entity.entity_type_id</code>.
     */
    public Integer getEntityTypeId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EntityRecord
     */
    public EntityRecord() {
        super(Entity.ENTITY);
    }

    /**
     * Create a detached, initialised EntityRecord
     */
    public EntityRecord(Integer id, String value, Integer entityTypeId) {
        super(Entity.ENTITY);

        setId(id);
        setValue(value);
        setEntityTypeId(entityTypeId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised EntityRecord
     */
    public EntityRecord(com.example.news.api.jooq.tables.pojos.Entity value) {
        super(Entity.ENTITY);

        if (value != null) {
            setId(value.getId());
            setValue(value.getValue());
            setEntityTypeId(value.getEntityTypeId());
            resetChangedOnNotNull();
        }
    }
}
