/*
 * This file is generated by jOOQ.
 */
package com.example.news.api.jooq.tables.records;


import com.example.news.api.jooq.tables.NewsEntity;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NewsEntityRecord extends UpdatableRecordImpl<NewsEntityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.news_entity.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.news_entity.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.news_entity.news_id</code>.
     */
    public void setNewsId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.news_entity.news_id</code>.
     */
    public Integer getNewsId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.news_entity.entity_id</code>.
     */
    public void setEntityId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.news_entity.entity_id</code>.
     */
    public Integer getEntityId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NewsEntityRecord
     */
    public NewsEntityRecord() {
        super(NewsEntity.NEWS_ENTITY);
    }

    /**
     * Create a detached, initialised NewsEntityRecord
     */
    public NewsEntityRecord(Integer id, Integer newsId, Integer entityId) {
        super(NewsEntity.NEWS_ENTITY);

        setId(id);
        setNewsId(newsId);
        setEntityId(entityId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised NewsEntityRecord
     */
    public NewsEntityRecord(com.example.news.api.jooq.tables.pojos.NewsEntity value) {
        super(NewsEntity.NEWS_ENTITY);

        if (value != null) {
            setId(value.getId());
            setNewsId(value.getNewsId());
            setEntityId(value.getEntityId());
            resetChangedOnNotNull();
        }
    }
}
