/*
 * This file is generated by jOOQ.
 */
package com.example.news.api.jooq.tables.records;


import com.example.news.api.jooq.tables.News;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NewsRecord extends UpdatableRecordImpl<NewsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.news.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.news.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.news.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.news.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.news.publish_date</code>.
     */
    public void setPublishDate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.news.publish_date</code>.
     */
    public LocalDateTime getPublishDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.news.link</code>.
     */
    public void setLink(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.news.link</code>.
     */
    public String getLink() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.news.lang</code>.
     */
    public void setLang(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.news.lang</code>.
     */
    public String getLang() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.news.full_text</code>.
     */
    public void setFullText(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.news.full_text</code>.
     */
    public String getFullText() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.news.summary</code>.
     */
    public void setSummary(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.news.summary</code>.
     */
    public String getSummary() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.news.sentiment_label</code>.
     */
    public void setSentimentLabel(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.news.sentiment_label</code>.
     */
    public String getSentimentLabel() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.news.sentiment</code>.
     */
    public void setSentiment(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.news.sentiment</code>.
     */
    public BigDecimal getSentiment() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>public.news.topic_id</code>.
     */
    public void setTopicId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.news.topic_id</code>.
     */
    public Integer getTopicId() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.news.source_id</code>.
     */
    public void setSourceId(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.news.source_id</code>.
     */
    public Integer getSourceId() {
        return (Integer) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NewsRecord
     */
    public NewsRecord() {
        super(News.NEWS);
    }

    /**
     * Create a detached, initialised NewsRecord
     */
    public NewsRecord(Integer id, String title, LocalDateTime publishDate, String link, String lang, String fullText, String summary, String sentimentLabel, BigDecimal sentiment, Integer topicId, Integer sourceId) {
        super(News.NEWS);

        setId(id);
        setTitle(title);
        setPublishDate(publishDate);
        setLink(link);
        setLang(lang);
        setFullText(fullText);
        setSummary(summary);
        setSentimentLabel(sentimentLabel);
        setSentiment(sentiment);
        setTopicId(topicId);
        setSourceId(sourceId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised NewsRecord
     */
    public NewsRecord(com.example.news.api.jooq.tables.pojos.News value) {
        super(News.NEWS);

        if (value != null) {
            setId(value.getId());
            setTitle(value.getTitle());
            setPublishDate(value.getPublishDate());
            setLink(value.getLink());
            setLang(value.getLang());
            setFullText(value.getFullText());
            setSummary(value.getSummary());
            setSentimentLabel(value.getSentimentLabel());
            setSentiment(value.getSentiment());
            setTopicId(value.getTopicId());
            setSourceId(value.getSourceId());
            resetChangedOnNotNull();
        }
    }
}
