/*
 * This file is generated by jOOQ.
 */
package com.example.news.api.jooq;


import com.example.news.api.jooq.tables.Entity;
import com.example.news.api.jooq.tables.EntityEntity;
import com.example.news.api.jooq.tables.EntityType;
import com.example.news.api.jooq.tables.News;
import com.example.news.api.jooq.tables.NewsEntity;
import com.example.news.api.jooq.tables.Source;
import com.example.news.api.jooq.tables.Topic;
import com.example.news.api.jooq.tables.records.EntityEntityRecord;
import com.example.news.api.jooq.tables.records.EntityRecord;
import com.example.news.api.jooq.tables.records.EntityTypeRecord;
import com.example.news.api.jooq.tables.records.NewsEntityRecord;
import com.example.news.api.jooq.tables.records.NewsRecord;
import com.example.news.api.jooq.tables.records.SourceRecord;
import com.example.news.api.jooq.tables.records.TopicRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<EntityRecord> ENTITY_PKEY = Internal.createUniqueKey(Entity.ENTITY, DSL.name("entity_pkey"), new TableField[] { Entity.ENTITY.ID }, true);
    public static final UniqueKey<EntityRecord> ENTITY_VALUE_KEY = Internal.createUniqueKey(Entity.ENTITY, DSL.name("entity_value_key"), new TableField[] { Entity.ENTITY.VALUE }, true);
    public static final UniqueKey<EntityEntityRecord> ENTITY_ENTITY_PKEY = Internal.createUniqueKey(EntityEntity.ENTITY_ENTITY, DSL.name("entity_entity_pkey"), new TableField[] { EntityEntity.ENTITY_ENTITY.ID }, true);
    public static final UniqueKey<EntityTypeRecord> ENTITY_TYPE_PKEY = Internal.createUniqueKey(EntityType.ENTITY_TYPE, DSL.name("entity_type_pkey"), new TableField[] { EntityType.ENTITY_TYPE.ID }, true);
    public static final UniqueKey<EntityTypeRecord> ENTITY_TYPE_UNIQUE_TYPE = Internal.createUniqueKey(EntityType.ENTITY_TYPE, DSL.name("entity_type_unique_type"), new TableField[] { EntityType.ENTITY_TYPE.NAME }, true);
    public static final UniqueKey<NewsRecord> NEWS_LINK_KEY = Internal.createUniqueKey(News.NEWS, DSL.name("news_link_key"), new TableField[] { News.NEWS.LINK }, true);
    public static final UniqueKey<NewsRecord> NEWS_PKEY = Internal.createUniqueKey(News.NEWS, DSL.name("news_pkey"), new TableField[] { News.NEWS.ID }, true);
    public static final UniqueKey<NewsEntityRecord> NEWS_ENTITY_NEWS_ID_ENTITY_ID_KEY = Internal.createUniqueKey(NewsEntity.NEWS_ENTITY, DSL.name("news_entity_news_id_entity_id_key"), new TableField[] { NewsEntity.NEWS_ENTITY.NEWS_ID, NewsEntity.NEWS_ENTITY.ENTITY_ID }, true);
    public static final UniqueKey<NewsEntityRecord> NEWS_ENTITY_PKEY = Internal.createUniqueKey(NewsEntity.NEWS_ENTITY, DSL.name("news_entity_pkey"), new TableField[] { NewsEntity.NEWS_ENTITY.ID }, true);
    public static final UniqueKey<SourceRecord> NEWS_SOURCE_PKEY = Internal.createUniqueKey(Source.SOURCE, DSL.name("news_source_pkey"), new TableField[] { Source.SOURCE.ID }, true);
    public static final UniqueKey<SourceRecord> NEWS_SOURCE_SOURCE_KEY = Internal.createUniqueKey(Source.SOURCE, DSL.name("news_source_source_key"), new TableField[] { Source.SOURCE.NAME }, true);
    public static final UniqueKey<TopicRecord> NEWS_CLASSIFICATION_CLASSIFICATION_KEY = Internal.createUniqueKey(Topic.TOPIC, DSL.name("news_classification_classification_key"), new TableField[] { Topic.TOPIC.NAME }, true);
    public static final UniqueKey<TopicRecord> NEWS_CLASSIFICATION_PKEY = Internal.createUniqueKey(Topic.TOPIC, DSL.name("news_classification_pkey"), new TableField[] { Topic.TOPIC.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<EntityRecord, EntityTypeRecord> ENTITY__ENTITY_ENTITY_TYPE_ID_FKEY = Internal.createForeignKey(Entity.ENTITY, DSL.name("entity_entity_type_id_fkey"), new TableField[] { Entity.ENTITY.ENTITY_TYPE_ID }, Keys.ENTITY_TYPE_PKEY, new TableField[] { EntityType.ENTITY_TYPE.ID }, true);
    public static final ForeignKey<NewsRecord, SourceRecord> NEWS__NEWS_SOURCE_ID_FKEY = Internal.createForeignKey(News.NEWS, DSL.name("news_source_id_fkey"), new TableField[] { News.NEWS.SOURCE_ID }, Keys.NEWS_SOURCE_PKEY, new TableField[] { Source.SOURCE.ID }, true);
    public static final ForeignKey<NewsRecord, TopicRecord> NEWS__NEWS_TOPIC_ID_FKEY = Internal.createForeignKey(News.NEWS, DSL.name("news_topic_id_fkey"), new TableField[] { News.NEWS.TOPIC_ID }, Keys.NEWS_CLASSIFICATION_PKEY, new TableField[] { Topic.TOPIC.ID }, true);
    public static final ForeignKey<NewsEntityRecord, EntityRecord> NEWS_ENTITY__NEWS_ENTITY_ENTITY_ID_FKEY = Internal.createForeignKey(NewsEntity.NEWS_ENTITY, DSL.name("news_entity_entity_id_fkey"), new TableField[] { NewsEntity.NEWS_ENTITY.ENTITY_ID }, Keys.ENTITY_PKEY, new TableField[] { Entity.ENTITY.ID }, true);
    public static final ForeignKey<NewsEntityRecord, NewsRecord> NEWS_ENTITY__NEWS_ENTITY_NEWS_ID_FKEY = Internal.createForeignKey(NewsEntity.NEWS_ENTITY, DSL.name("news_entity_news_id_fkey"), new TableField[] { NewsEntity.NEWS_ENTITY.NEWS_ID }, Keys.NEWS_PKEY, new TableField[] { News.NEWS.ID }, true);
}
