/*
 * This file is generated by jOOQ.
 */
package com.example.news.api.jooq;


import com.example.news.api.jooq.tables.Entity;
import com.example.news.api.jooq.tables.EntityEntity;
import com.example.news.api.jooq.tables.EntityType;
import com.example.news.api.jooq.tables.News;
import com.example.news.api.jooq.tables.NewsEntity;
import com.example.news.api.jooq.tables.Source;
import com.example.news.api.jooq.tables.Topic;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.entity</code>.
     */
    public final Entity ENTITY = Entity.ENTITY;

    /**
     * The table <code>public.entity_entity</code>.
     */
    public final EntityEntity ENTITY_ENTITY = EntityEntity.ENTITY_ENTITY;

    /**
     * The table <code>public.entity_type</code>.
     */
    public final EntityType ENTITY_TYPE = EntityType.ENTITY_TYPE;

    /**
     * The table <code>public.news</code>.
     */
    public final News NEWS = News.NEWS;

    /**
     * The table <code>public.news_entity</code>.
     */
    public final NewsEntity NEWS_ENTITY = NewsEntity.NEWS_ENTITY;

    /**
     * The table <code>public.source</code>.
     */
    public final Source SOURCE = Source.SOURCE;

    /**
     * The table <code>public.topic</code>.
     */
    public final Topic TOPIC = Topic.TOPIC;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.NEWS_CLASSIFICATION_ID_SEQ,
            Sequences.NEWS_SOURCE_ID_SEQ
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Entity.ENTITY,
            EntityEntity.ENTITY_ENTITY,
            EntityType.ENTITY_TYPE,
            News.NEWS,
            NewsEntity.NEWS_ENTITY,
            Source.SOURCE,
            Topic.TOPIC
        );
    }
}
