/*
 * This file is generated by jOOQ.
 */
package com.example.news.api.jooq;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.news_classification_id_seq</code>
     */
    public static final Sequence<Integer> NEWS_CLASSIFICATION_ID_SEQ = Internal.createSequence("news_classification_id_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.news_source_id_seq</code>
     */
    public static final Sequence<Integer> NEWS_SOURCE_ID_SEQ = Internal.createSequence("news_source_id_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);
}
