/*
 * This file is generated by jOOQ.
 */
package com.example.news.api.jooq;


import com.example.news.api.jooq.tables.Entity;
import com.example.news.api.jooq.tables.EntityEntity;
import com.example.news.api.jooq.tables.EntityType;
import com.example.news.api.jooq.tables.News;
import com.example.news.api.jooq.tables.NewsEntity;
import com.example.news.api.jooq.tables.Source;
import com.example.news.api.jooq.tables.Topic;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.entity</code>.
     */
    public static final Entity ENTITY = Entity.ENTITY;

    /**
     * The table <code>public.entity_entity</code>.
     */
    public static final EntityEntity ENTITY_ENTITY = EntityEntity.ENTITY_ENTITY;

    /**
     * The table <code>public.entity_type</code>.
     */
    public static final EntityType ENTITY_TYPE = EntityType.ENTITY_TYPE;

    /**
     * The table <code>public.news</code>.
     */
    public static final News NEWS = News.NEWS;

    /**
     * The table <code>public.news_entity</code>.
     */
    public static final NewsEntity NEWS_ENTITY = NewsEntity.NEWS_ENTITY;

    /**
     * The table <code>public.source</code>.
     */
    public static final Source SOURCE = Source.SOURCE;

    /**
     * The table <code>public.topic</code>.
     */
    public static final Topic TOPIC = Topic.TOPIC;
}
