import SignificantTermsAggregationCard
  from '@/components/Overview/EntityTopicIntelligenceBreakdown/SignificantTermsAggregation/SignificantTermsAggregationCard.tsx';

export default SignificantTermsAggregationCard;